### ISSUE TITLE
Executable permissions are lost when converting to wheel to conda package

### ISSUE THREAD

**Issue by gilfree** [zuzukin/whl2conda#135]
**Describe the bug**
If a wheel file contains a file with executable permissions - they will be lost when converting to a conda package.

**To Reproduce**
Create a python package with a script that has executable permission (chmod +x) and convert to conda. 

**Expected behavior**
The executable permissions should be kept.

The root cause of the bug is in here: https://github.com/pypa/wheel/issues/608.
To fix it, until `wheel` is fixed [_extract_wheel](https://github.com/zuzukin/whl2conda/blob/79c5a514f4cadcd28f5b4f1095638f51ff885972/src/whl2conda/api/converter.py#L886) method need to be updated:
```python
    def _extract_wheel(self, temp_dir: Path) -> Path:
        self.logger.info("Reading %s", self.wheel_path)
        wheel = WheelFile(self.wheel_path)
        wheel_dir = temp_dir / "wheel-files"
        wheel.extractall(wheel_dir)
```
To something along the lines of:

```python
   wheel_dir = temp_dir / "wheel-files"
    with WheelFile(self.wheel_path) as wf:
        namever = wf.parsed_filename.group("namever")
        for zinfo in wf.filelist:
            wf.extract(zinfo, destination)

            # Set permissions to the same values as they were set in the archive
            # We have to do this manually due to
            # https://github.com/python/cpython/issues/59999
            permissions = zinfo.external_attr >> 16 & 0o777
            wheel_dir.joinpath(zinfo.filename).chmod(permissions)
        if self.logger.getEffectiveLevel() <= logging.DEBUG:
            for wheel_file in wheel_dir.glob("**/*"):
                if wheel_file.is_file():
                    self._debug("Extracted %s", wheel_file.relative_to(wheel_dir))
        return wheel_dir
```

(Code taken from: https://github.com/pypa/wheel/blob/0a4f40ecf967757b43e2cdfd4b3c52b16d15614a/src/wheel/cli/unpack.py#L24)

**Desktop (please complete the following information):**
 - OS: linux
 - whl2conda version 24.1.2

**Additional context**

**Comment by analog-cbarber** [comment]
Thanks for the report!

Obviously, the lazy solution is to wait for this to get fixed in wheel, but I am open to a PR if you want to submit one.

If you do, I think you should provide an `_extract_all` function that will act as a drop-in replacement for
`wheel.extractall` and also make sure to provide a test case.

**Comment by analog-cbarber** [comment]
I should update the wheel dependency when this fix is available...

**Comment by agronholm** [comment]
I must point out that `wheel` does not currently have a public API, so making a tool that imports `wheel` is currently dubious. Is there no way to use its CLI instead?

**Comment by analog-cbarber** [comment]
Another issue with `wheel unpack` is that it unpacks into a subdirectory of the dest dir with name parsed from the wheel file name, so I would have to deal with that extra subdir.

**Comment by analog-cbarber** [comment]
Another issue with file permissions is that is not really supported on Windows. On windows calling `chmod()` won't have any effect for the permission bits, so if you run the conversion on Windows it will still throw away the file permissions. I think that fixing that would require actually going into the conda zip compression code and probably would not be practical to fix.

**Comment by gilfree** [comment]
Thanks!
